### ISSUE TITLE
Refactor/Add tests for specific responses

### ISSUE THREAD

**Issue by FWidm** [FWidm/discord-pob#6]
Not only test whether a response object could be done but also check if the appropriate things happens when parsing an xml build.

For example dot damage not displaying attack speed or a build with >5 auras being recognized as support.

**Comment by FWidm** [comment]
First base skeleton added #7

**Comment by FWidm** [comment]
Refined base #9

**Comment by sommermi** [comment]
Du hast Urlaub und hier gibt es einen open issue? ;-)

**Comment by FWidm** [comment]
Eine wahre Farce :D

**Comment by sommermi** [comment]
Du hast schon wieder Urlaub und der Issue ist immer noch offen?
